-- name/emailはRegisterRequestのアプリ側上限(30文字/100文字)に合わせる。
-- token_hashはSHA-256を16進数化した値で常に64文字固定のため64に合わせる。
CREATE TABLE pending_registrations (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(30) NOT NULL,
    email         VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    token_hash    VARCHAR(64) NOT NULL,
    expires_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_pending_registrations_email UNIQUE (email),
    CONSTRAINT uk_pending_registrations_token_hash UNIQUE (token_hash)
);
