-- パスワードリセット専用のtokenテーブル。メール認証用のpending_registrationsとは分離する。
-- 1ユーザーにつき有効tokenは1件までとするため、user_idをUNIQUEにする(再発行は上書き更新)。
-- token_hashはSHA-256を16進数化した値で常に64文字固定のため64に合わせる。
CREATE TABLE password_reset_tokens (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL,
    token_hash    VARCHAR(64) NOT NULL,
    expires_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_password_reset_tokens_user_id UNIQUE (user_id),
    CONSTRAINT uk_password_reset_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_password_reset_tokens_user_id FOREIGN KEY (user_id) REFERENCES users (id)
);
