-- メールアドレス変更申請専用のtokenテーブル。メール認証用のpending_registrations、
-- パスワードリセット用のpassword_reset_tokensとは分離する。
-- 1ユーザーにつき有効な申請は1件までとするため、user_idをUNIQUEにする(再申請は上書き更新)。
-- new_emailにもUNIQUE制約を付け、Service層の事前確認(アプリ側)と合わせて
-- 同時リクエストによる競合(2ユーザーが同じnew_emailを同時に確認なしで保存する)を
-- DBレベルでも防ぐ。事前確認をすり抜けた場合はDB制約違反(DataIntegrityViolationException)
-- となり、GlobalExceptionHandlerで409として扱う。
CREATE TABLE email_change_requests (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL,
    new_email    VARCHAR(100) NOT NULL,
    token_hash   VARCHAR(64) NOT NULL,
    expires_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_email_change_requests_user_id UNIQUE (user_id),
    CONSTRAINT uk_email_change_requests_new_email UNIQUE (new_email),
    CONSTRAINT uk_email_change_requests_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_email_change_requests_user_id FOREIGN KEY (user_id) REFERENCES users (id)
);
