-- Googleログイン(OpenID Connect)用。usersへプロバイダ専用カラムを直接追加せず、
-- 将来LINE等の追加プロバイダにも対応できるよう外部認証情報を別テーブルへ分離する。
-- provider_user_idはGoogleの場合はOIDCの"sub"claim(不変の外部アカウント識別子)。
-- provider+provider_user_idのUNIQUEで同一外部アカウントの重複紐付けを防ぎ、
-- user_id+providerのUNIQUEで同一ユーザーが同じプロバイダで複数紐付くことを防ぐ。
CREATE TABLE oauth_accounts (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT NOT NULL,
    provider          VARCHAR(20) NOT NULL,
    provider_user_id  VARCHAR(255) NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_oauth_accounts_provider_user UNIQUE (provider, provider_user_id),
    CONSTRAINT uk_oauth_accounts_user_provider UNIQUE (user_id, provider),
    CONSTRAINT fk_oauth_accounts_user_id FOREIGN KEY (user_id) REFERENCES users (id)
);
